name: Linter
on: [pull_request]

jobs:
  ruby-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@v2.0.0
      with:
        additional_gems: 'rubocop-performance'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  js-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1.9.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          eslint_flags: 'dist/**/* webpack.config.js'
          fail_on_error: true

  css-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: stylelint
        uses: reviewdog/action-stylelint@v1.7.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          stylelint_input: 'dist/**/*.scss'
  
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: stylelint
      uses: prologic/action-markdownlint@v0.1
      with:
        reporter: github-check
